CREATE DATABASE Assetly;
USE Assetly;

CREATE TABLE USER_STOCKS (
	STOCK_ID VARCHAR(5) PRIMARY KEY,
    STOCK_NAME VARCHAR(50),
    QUANTITY INT,
    PRICE INT,
    SECTOR VARCHAR(50),
    PURCHASE_DATE DATE,
    AMOUNT INT
);

CREATE TABLE USER_GOLD(
	PRICE INT,
    WEIGHT INT,
    PURCHASE_DATE DATE,
    AMOUNT INT
);