CREATE DATABASE Assetly;
USE Assetly;

CREATE TABLE USER_STOCKS (
	 ID INT AUTO_INCREMENT PRIMARY KEY,
	STOCK_ID VARCHAR(5) NOT NULL,
    STOCK_NAME VARCHAR(50) NOT NULL,
    QUANTITY DECIMAL(10, 2) NOT NULL,
    PRICE INT NOT NULL,
    SECTOR VARCHAR(50) NOT NULL,
    PURCHASE_DATE DATE NOT NULL,
    AMOUNT DECIMAL(15,2) GENERATED ALWAYS AS (quantity * price) STORED,
);

CREATE TABLE USER_GOLD(
	PRICE INT,
    WEIGHT INT,
    PURCHASE_DATE DATE,
    AMOUNT INT
);
